package del.ac.id.controller;

//import del.ac.id.model.ListUser;
import del.ac.id.model.User;
import del.ac.id.repository.UserRepository;
import del.ac.id.request.RegisterRequest;
//import del.ac.id.service.ListUserService;
import del.ac.id.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;
import org.springframework.web.servlet.view.RedirectView;

import java.sql.Date;
import java.time.Instant;
import java.time.LocalDateTime;
import java.util.List;

@Controller
public class UserController {
     // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    UserService service;

    @RequestMapping("/")
    public String home(Model model){
//        userService.save(new RegisterRequest("a","a","a",RoleName.ROLE_ADMIN));

        RegisterRequest user = new RegisterRequest();
//        status.setComplete();
        model.addAttribute("user",user);

        return "home";
    }
    @RequestMapping(value = "/save",method = RequestMethod.POST)
    public RedirectView login(@ModelAttribute("user")RegisterRequest register , Model model, RedirectAttributes redirectAttributes){
        User user = service.checkLogin(register.getUsername(),register.getPassword());
        if(user==null){
            RedirectView mav = new RedirectView("/",true);

            return mav;
        }

        RedirectView mav = new RedirectView("/dashboard",false);
        redirectAttributes.addAttribute("user",user);
        return mav;
    }
    @RequestMapping("/dashboard")
    public ModelAndView dashboard(@ModelAttribute("user") User user,Model model){
        ModelAndView modelAndView = new ModelAndView("dashboard");
        modelAndView.addObject("user1",model.asMap().get("user"));
//        User user = service.checkLogin(register.getUsername(),register.getPassword());
//        model.addAttribute("user",user);
        return modelAndView;
    }
}
