package del.ac.id.controller;

//import del.ac.id.model.ListUser;
import del.ac.id.model.User;
import del.ac.id.repository.UserRepository;
import del.ac.id.request.RegisterRequest;
//import del.ac.id.service.ListUserService;
import del.ac.id.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import java.sql.Date;
import java.time.Instant;
import java.time.LocalDateTime;
import java.util.List;

@Controller
public class UserController {
     // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    UserService service;

    @RequestMapping("/")
    public String home(Model model){
        List<User> user = service.findAll();
        model.addAttribute("listuser",user);
        return "berhasil";
    }
    @RequestMapping("/new")
    public String register(Model model){
        RegisterRequest request = new RegisterRequest();
        model.addAttribute("request",request);
        return "new_user";
    }
    @RequestMapping(value = "/save", method = RequestMethod.POST)
    public String saveProduct(@ModelAttribute("request") RegisterRequest request) {
        service.save(request);

        return "redirect:/";
    }

}
